name = "thienkim"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "tk-pipeline-db"
database_id = "bf87b50e-767e-42d6-ad1b-62565a9b403a"
